package frc.robot;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.hardware.*;
import com.ctre.phoenix6.signals.*;
import com.ctre.phoenix6.swerve.*;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.*;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.interpolation.InterpolatingDoubleTreeMap;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.*;

import frc.robot.subsystems.CommandSwerveDrivetrain;

// Generated by the 2026 Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class Constants {

    // ===== FIELD CONSTANTS =====
    // Hub positions and pass points in WPILib Blue Alliance coordinates.
    public static final Translation2d BLUE_HUB        = new Translation2d(4.6256, 4.0346);
    public static final Translation2d RED_HUB         = new Translation2d(11.9154, 4.0346);
    public static final Translation2d BLUE_PASS_LEFT  = new Translation2d(1.0, 7.0);
    public static final Translation2d BLUE_PASS_RIGHT = new Translation2d(1.0, 1.0);
    public static final Translation2d RED_PASS_LEFT   = new Translation2d(15.5, 1.0);
    public static final Translation2d RED_PASS_RIGHT  = new Translation2d(15.5, 7.0);

    // ===== AIM ZONE BOUNDARIES =====
    public static final double BLUE_HUB_MAX_X = 3.978;
    public static final double RED_HUB_MIN_X  = 12.563;
    public static final double PASS_SPLIT_Y   = 4.035;

    // ===== SHOOTER CONSTANTS =====
    public static final double SHOOTER_ANGLE_OFFSET_DEG = 90.0;

    // ===== DISTANCE-TO-SPEED LOOKUP TABLE =====
    // Maps distance (meters) → flywheel speed in Rotations Per Second (RPS).
    public static final InterpolatingDoubleTreeMap SHOOTER_SPEED_MAP =
        new InterpolatingDoubleTreeMap();
    static {
        SHOOTER_SPEED_MAP.put(1.5, 60.0); // >>> TEST THIS <<<
        SHOOTER_SPEED_MAP.put(3.0, 65.0); // ✓ Confirmed
        SHOOTER_SPEED_MAP.put(5.8, 90.0); // >>> TEST THIS <<<
        SHOOTER_SPEED_MAP.put(7.0, 95.0); // >>> TEST THIS <<<
    }

    // ===== SHOT LEADING =====
    public static final double BALL_SPEED_MPS = 12.0;

    // =========================================================================
    // KNOWN POSE RESET POSITIONS  (Request #4)
    // =========================================================================
    // Use these with the Start + Left Bumper button combo.
    //
    // HOW TO USE:
    //   1. During a match (or in testing), drive your robot to a specific
    //      spot on the field where you KNOW the exact coordinates.
    //      A good choice is the edge of your alliance's community zone,
    //      a known line on the carpet, or a wall corner.
    //   2. Press Start + Left Bumper on the gamepad.
    //   3. The robot's pose (X and Y position) will snap to the coordinates
    //      below, while keeping the current gyro heading.
    //
    // WHY THIS IS USEFUL:
    //   If wheel odometry has drifted over time, or you didn't get good
    //   AprilTag data early in the match, this lets you "re-anchor" to
    //   a known landmark. Think of it like a GPS recalibration.
    //
    // COORDINATES ARE IN WPILib BLUE ALLIANCE COORDINATE SYSTEM:
    //   - X = 0 is the Blue alliance wall, increases toward Red wall
    //   - Y = 0 is the bottom wall (when looking from above in standard orientation)
    //   - X = ~16.54m is the Red alliance wall
    //
    // *** YOU MUST CHANGE THESE TO MATCH YOUR ACTUAL RESET SPOT! ***
    // The values below are just example starting points.
    //
    // Tip: drive to a spot, look at AdvantageScope/Elastic for the current
    // pose, and copy those X,Y numbers in here.
    // =========================================================================

    /**
     * Blue Alliance known reset position.
     *
     * Example: A spot near the Blue subwoofer that you can reliably drive to.
     * X ≈ 1.5m from Blue wall, Y ≈ 5.5m (upper area near the hub)
     *
     * CHANGE THESE X,Y VALUES to match your actual chosen reset spot!
     */
    public static final Translation2d BLUE_RESET_POSITION =
        new Translation2d(1.5, 5.5);  // ← *** CHANGE THESE ***

    /**
     * Red Alliance known reset position.
     *
     * When on Red alliance, the field is mirrored.
     * X ≈ 15.0m (near Red wall), Y ≈ 5.5m
     *
     * CHANGE THESE X,Y VALUES to match your actual chosen reset spot!
     */
    public static final Translation2d RED_RESET_POSITION =
        new Translation2d(15.0, 5.5); // ← *** CHANGE THESE ***

    // =========================================================================
    // END OF KNOWN POSE RESET POSITIONS
    // =========================================================================

    // Both sets of gains need to be tuned to your individual robot.
    private static final Slot0Configs steerGains = new Slot0Configs()
        .withKP(100).withKI(0).withKD(0.5)
        .withKS(0.1).withKV(2.66).withKA(0)
        .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);

    private static final Slot0Configs driveGains = new Slot0Configs()
        .withKP(0.1).withKI(0).withKD(0)
        .withKS(0).withKV(0.124);

    private static final ClosedLoopOutputType kSteerClosedLoopOutput = ClosedLoopOutputType.Voltage;
    private static final ClosedLoopOutputType kDriveClosedLoopOutput = ClosedLoopOutputType.Voltage;
    private static final DriveMotorArrangement kDriveMotorType = DriveMotorArrangement.TalonFX_Integrated;
    private static final SteerMotorArrangement kSteerMotorType = SteerMotorArrangement.TalonFX_Integrated;
    private static final SteerFeedbackType kSteerFeedbackType = SteerFeedbackType.FusedCANcoder;
    private static final Current kSlipCurrent = Amps.of(120);

    private static final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration();
    private static final TalonFXConfiguration steerInitialConfigs = new TalonFXConfiguration()
        .withCurrentLimits(
            new CurrentLimitsConfigs()
                .withStatorCurrentLimit(Amps.of(60))
                .withStatorCurrentLimitEnable(true)
        );
    private static final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
    private static final Pigeon2Configuration pigeonConfigs = null;

    public static final CANBus kCANBus = new CANBus("Canivore", "./logs/example.hoot");
    public static final LinearVelocity kSpeedAt12Volts = MetersPerSecond.of(5.04);

    private static final double kCoupleRatio    = 3.5714285714285716;
    private static final double kDriveGearRatio = 6.122448979591837;
    private static final double kSteerGearRatio = 21.428571428571427;
    private static final Distance kWheelRadius  = Inches.of(2);

    private static final boolean kInvertLeftSide  = false;
    private static final boolean kInvertRightSide = true;
    private static final int kPigeonId = 0;

    private static final MomentOfInertia kSteerInertia       = KilogramSquareMeters.of(0.01);
    private static final MomentOfInertia kDriveInertia       = KilogramSquareMeters.of(0.01);
    private static final Voltage kSteerFrictionVoltage       = Volts.of(0.2);
    private static final Voltage kDriveFrictionVoltage       = Volts.of(0.2);

    public static final SwerveDrivetrainConstants DrivetrainConstants = new SwerveDrivetrainConstants()
        .withCANBusName(kCANBus.getName())
        .withPigeon2Id(kPigeonId)
        .withPigeon2Configs(pigeonConfigs);

    private static final SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> ConstantCreator =
        new SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
            .withDriveMotorGearRatio(kDriveGearRatio)
            .withSteerMotorGearRatio(kSteerGearRatio)
            .withCouplingGearRatio(kCoupleRatio)
            .withWheelRadius(kWheelRadius)
            .withSteerMotorGains(steerGains)
            .withDriveMotorGains(driveGains)
            .withSteerMotorClosedLoopOutput(kSteerClosedLoopOutput)
            .withDriveMotorClosedLoopOutput(kDriveClosedLoopOutput)
            .withSlipCurrent(kSlipCurrent)
            .withSpeedAt12Volts(kSpeedAt12Volts)
            .withDriveMotorType(kDriveMotorType)
            .withSteerMotorType(kSteerMotorType)
            .withFeedbackSource(kSteerFeedbackType)
            .withDriveMotorInitialConfigs(driveInitialConfigs)
            .withSteerMotorInitialConfigs(steerInitialConfigs)
            .withEncoderInitialConfigs(encoderInitialConfigs)
            .withSteerInertia(kSteerInertia)
            .withDriveInertia(kDriveInertia)
            .withSteerFrictionVoltage(kSteerFrictionVoltage)
            .withDriveFrictionVoltage(kDriveFrictionVoltage);

    // Front Left
    private static final int     kFrontLeftDriveMotorId      = 43;
    private static final int     kFrontLeftSteerMotorId      = 41;
    private static final int     kFrontLeftEncoderId         = 42;
    private static final Angle   kFrontLeftEncoderOffset     = Rotations.of(-0.22216796875);
    private static final boolean kFrontLeftSteerMotorInverted = true;
    private static final boolean kFrontLeftEncoderInverted   = false;
    private static final Distance kFrontLeftXPos             = Inches.of(10.875);
    private static final Distance kFrontLeftYPos             = Inches.of(10.875);

    // Front Right
    private static final int     kFrontRightDriveMotorId      = 13;
    private static final int     kFrontRightSteerMotorId      = 11;
    private static final int     kFrontRightEncoderId         = 12;
    private static final Angle   kFrontRightEncoderOffset     = Rotations.of(-0.213623046875);
    private static final boolean kFrontRightSteerMotorInverted = true;
    private static final boolean kFrontRightEncoderInverted   = false;
    private static final Distance kFrontRightXPos             = Inches.of(10.875);
    private static final Distance kFrontRightYPos             = Inches.of(-10.875);

    // Back Left
    private static final int     kBackLeftDriveMotorId      = 33;
    private static final int     kBackLeftSteerMotorId      = 31;
    private static final int     kBackLeftEncoderId         = 32;
    private static final Angle   kBackLeftEncoderOffset     = Rotations.of(-0.13037109375);
    private static final boolean kBackLeftSteerMotorInverted = true;
    private static final boolean kBackLeftEncoderInverted   = false;
    private static final Distance kBackLeftXPos             = Inches.of(-10.875);
    private static final Distance kBackLeftYPos             = Inches.of(10.875);

    // Back Right
    private static final int     kBackRightDriveMotorId      = 23;
    private static final int     kBackRightSteerMotorId      = 21;
    private static final int     kBackRightEncoderId         = 22;
    private static final Angle   kBackRightEncoderOffset     = Rotations.of(-0.453857421875);
    private static final boolean kBackRightSteerMotorInverted = true;
    private static final boolean kBackRightEncoderInverted   = false;
    private static final Distance kBackRightXPos             = Inches.of(-10.875);
    private static final Distance kBackRightYPos             = Inches.of(-10.875);

    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontLeft =
        ConstantCreator.createModuleConstants(
            kFrontLeftSteerMotorId, kFrontLeftDriveMotorId, kFrontLeftEncoderId, kFrontLeftEncoderOffset,
            kFrontLeftXPos, kFrontLeftYPos, kInvertLeftSide, kFrontLeftSteerMotorInverted, kFrontLeftEncoderInverted
        );

    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontRight =
        ConstantCreator.createModuleConstants(
            kFrontRightSteerMotorId, kFrontRightDriveMotorId, kFrontRightEncoderId, kFrontRightEncoderOffset,
            kFrontRightXPos, kFrontRightYPos, kInvertRightSide, kFrontRightSteerMotorInverted, kFrontRightEncoderInverted
        );

    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackLeft =
        ConstantCreator.createModuleConstants(
            kBackLeftSteerMotorId, kBackLeftDriveMotorId, kBackLeftEncoderId, kBackLeftEncoderOffset,
            kBackLeftXPos, kBackLeftYPos, kInvertLeftSide, kBackLeftSteerMotorInverted, kBackLeftEncoderInverted
        );

    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackRight =
        ConstantCreator.createModuleConstants(
            kBackRightSteerMotorId, kBackRightDriveMotorId, kBackRightEncoderId, kBackRightEncoderOffset,
            kBackRightXPos, kBackRightYPos, kInvertRightSide, kBackRightSteerMotorInverted, kBackRightEncoderInverted
        );

    /**
     * Creates a CommandSwerveDrivetrain instance.
     * This should only be called once in your robot program.
     */
    public static CommandSwerveDrivetrain createDrivetrain() {
        return new CommandSwerveDrivetrain(
            DrivetrainConstants, FrontLeft, FrontRight, BackLeft, BackRight
        );
    }

    /**
     * Swerve Drive class utilizing CTR Electronics' Phoenix 6 API with the selected device types.
     */
    public static class TunerSwerveDrivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> {

        public TunerSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, modules
            );
        }

        public TunerSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, odometryUpdateFrequency, modules
            );
        }

        public TunerSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, odometryUpdateFrequency,
                odometryStandardDeviation, visionStandardDeviation, modules
            );
        }
    }
}